<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr">
    <head>
	<link rel="icon" type="image/png" href="RASoftware.png" >
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="author" content="Rachid AKKOUCHE" />
        <link rel="stylesheet" type="text/css" href="style.css" />
        <script type="text/javascript" src="javascript.js"></script>
