        <table border="1" class="centrelarge">
            <tr class="lightblue">
                <th>Canal 1</th>
                <th>Canal 2</th>
                <th>Canal 3</th>
                <th>Canal 4</th>
                <th>Canal 5</th>
                <th>Canal 6</th>
                <th>Canal 7</th>
                <th>Canal 8</th>
                <th>Canal 9</th>
                <th>Canal 10</th>
                <th>Canal 11</th>
                <th>Canal 12</th>
                <th>Canal 13</th>
                <th>Canal 14</th>
                <th>Canal 15</th>
                <th>Canal 16</th>
            </tr>
